services:
  backend:
    build:
      context: ./apps/backend
    ports:
      - "3010:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:${DB_PASSWORD}@host.docker.internal:5432/control_gastos?schema=public
      - JWT_SECRET=cambia_este_valor_por_uno_seguro
      - JWT_EXPIRES_IN=2m
      - PORT=3000
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
    extra_hosts:
      - "host.docker.internal:host-gateway"

  frontend:
    build:
      context: ./apps/frontend
    ports:
      - "4201:80"
    depends_on:
      - backend